/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface SafeMigrationInterface extends utils.Interface {
  functions: {
    "MIGRATION_SINGLETON()": FunctionFragment;
    "SAFE_FALLBACK_HANDLER()": FunctionFragment;
    "SAFE_L2_SINGLETON()": FunctionFragment;
    "SAFE_SINGLETON()": FunctionFragment;
    "migrateL2Singleton()": FunctionFragment;
    "migrateL2WithFallbackHandler()": FunctionFragment;
    "migrateSingleton()": FunctionFragment;
    "migrateWithFallbackHandler()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MIGRATION_SINGLETON"
      | "SAFE_FALLBACK_HANDLER"
      | "SAFE_L2_SINGLETON"
      | "SAFE_SINGLETON"
      | "migrateL2Singleton"
      | "migrateL2WithFallbackHandler"
      | "migrateSingleton"
      | "migrateWithFallbackHandler"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MIGRATION_SINGLETON",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_FALLBACK_HANDLER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_L2_SINGLETON",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFE_SINGLETON",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrateL2Singleton",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrateL2WithFallbackHandler",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrateSingleton",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrateWithFallbackHandler",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MIGRATION_SINGLETON",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_FALLBACK_HANDLER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_L2_SINGLETON",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFE_SINGLETON",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateL2Singleton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateL2WithFallbackHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateSingleton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateWithFallbackHandler",
    data: BytesLike
  ): Result;

  events: {
    "ChangedMasterCopy(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChangedMasterCopy"): EventFragment;
}

export interface ChangedMasterCopyEventObject {
  singleton: string;
}
export type ChangedMasterCopyEvent = TypedEvent<
  [string],
  ChangedMasterCopyEventObject
>;

export type ChangedMasterCopyEventFilter =
  TypedEventFilter<ChangedMasterCopyEvent>;

export interface SafeMigration extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SafeMigrationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MIGRATION_SINGLETON(overrides?: CallOverrides): Promise<[string]>;

    SAFE_FALLBACK_HANDLER(overrides?: CallOverrides): Promise<[string]>;

    SAFE_L2_SINGLETON(overrides?: CallOverrides): Promise<[string]>;

    SAFE_SINGLETON(overrides?: CallOverrides): Promise<[string]>;

    migrateL2Singleton(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    migrateL2WithFallbackHandler(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    migrateSingleton(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    migrateWithFallbackHandler(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  MIGRATION_SINGLETON(overrides?: CallOverrides): Promise<string>;

  SAFE_FALLBACK_HANDLER(overrides?: CallOverrides): Promise<string>;

  SAFE_L2_SINGLETON(overrides?: CallOverrides): Promise<string>;

  SAFE_SINGLETON(overrides?: CallOverrides): Promise<string>;

  migrateL2Singleton(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  migrateL2WithFallbackHandler(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  migrateSingleton(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  migrateWithFallbackHandler(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    MIGRATION_SINGLETON(overrides?: CallOverrides): Promise<string>;

    SAFE_FALLBACK_HANDLER(overrides?: CallOverrides): Promise<string>;

    SAFE_L2_SINGLETON(overrides?: CallOverrides): Promise<string>;

    SAFE_SINGLETON(overrides?: CallOverrides): Promise<string>;

    migrateL2Singleton(overrides?: CallOverrides): Promise<void>;

    migrateL2WithFallbackHandler(overrides?: CallOverrides): Promise<void>;

    migrateSingleton(overrides?: CallOverrides): Promise<void>;

    migrateWithFallbackHandler(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "ChangedMasterCopy(address)"(
      singleton?: null
    ): ChangedMasterCopyEventFilter;
    ChangedMasterCopy(singleton?: null): ChangedMasterCopyEventFilter;
  };

  estimateGas: {
    MIGRATION_SINGLETON(overrides?: CallOverrides): Promise<BigNumber>;

    SAFE_FALLBACK_HANDLER(overrides?: CallOverrides): Promise<BigNumber>;

    SAFE_L2_SINGLETON(overrides?: CallOverrides): Promise<BigNumber>;

    SAFE_SINGLETON(overrides?: CallOverrides): Promise<BigNumber>;

    migrateL2Singleton(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    migrateL2WithFallbackHandler(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    migrateSingleton(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    migrateWithFallbackHandler(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MIGRATION_SINGLETON(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SAFE_FALLBACK_HANDLER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SAFE_L2_SINGLETON(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SAFE_SINGLETON(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    migrateL2Singleton(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    migrateL2WithFallbackHandler(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    migrateSingleton(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    migrateWithFallbackHandler(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
