"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimulateTxAccessor__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "to",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "value",
                type: "uint256",
            },
            {
                internalType: "bytes",
                name: "data",
                type: "bytes",
            },
            {
                internalType: "enum Enum.Operation",
                name: "operation",
                type: "uint8",
            },
        ],
        name: "simulate",
        outputs: [
            {
                internalType: "uint256",
                name: "estimate",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "success",
                type: "bool",
            },
            {
                internalType: "bytes",
                name: "returnData",
                type: "bytes",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
];
var SimulateTxAccessor__factory = /** @class */ (function () {
    function SimulateTxAccessor__factory() {
    }
    SimulateTxAccessor__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    SimulateTxAccessor__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    SimulateTxAccessor__factory.abi = _abi;
    return SimulateTxAccessor__factory;
}());
exports.SimulateTxAccessor__factory = SimulateTxAccessor__factory;
