"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SafeMigration__factory = exports.ISafe__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ISafe__factory_1 = require("./ISafe__factory");
Object.defineProperty(exports, "ISafe__factory", { enumerable: true, get: function () { return ISafe__factory_1.ISafe__factory; } });
var SafeMigration__factory_1 = require("./SafeMigration__factory");
Object.defineProperty(exports, "SafeMigration__factory", { enumerable: true, get: function () { return SafeMigration__factory_1.SafeMigration__factory; } });
