"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SafeMigration__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "safeSingleton",
                type: "address",
            },
            {
                internalType: "address",
                name: "safeL2Singleton",
                type: "address",
            },
            {
                internalType: "address",
                name: "fallbackHandler",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "singleton",
                type: "address",
            },
        ],
        name: "ChangedMasterCopy",
        type: "event",
    },
    {
        inputs: [],
        name: "MIGRATION_SINGLETON",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "SAFE_FALLBACK_HANDLER",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "SAFE_L2_SINGLETON",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "SAFE_SINGLETON",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "migrateL2Singleton",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "migrateL2WithFallbackHandler",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "migrateSingleton",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "migrateWithFallbackHandler",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
var SafeMigration__factory = /** @class */ (function () {
    function SafeMigration__factory() {
    }
    SafeMigration__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    SafeMigration__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    SafeMigration__factory.abi = _abi;
    return SafeMigration__factory;
}());
exports.SafeMigration__factory = SafeMigration__factory;
