"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mockContractSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.mockContractSol = require("./MockContract.sol");
