"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MultiSendCallOnly__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "bytes",
                name: "transactions",
                type: "bytes",
            },
        ],
        name: "multiSend",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
];
var MultiSendCallOnly__factory = /** @class */ (function () {
    function MultiSendCallOnly__factory() {
    }
    MultiSendCallOnly__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    MultiSendCallOnly__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    MultiSendCallOnly__factory.abi = _abi;
    return MultiSendCallOnly__factory;
}());
exports.MultiSendCallOnly__factory = MultiSendCallOnly__factory;
