"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MultiSend__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        inputs: [
            {
                internalType: "bytes",
                name: "transactions",
                type: "bytes",
            },
        ],
        name: "multiSend",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
];
var MultiSend__factory = /** @class */ (function () {
    function MultiSend__factory() {
    }
    MultiSend__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    MultiSend__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    MultiSend__factory.abi = _abi;
    return MultiSend__factory;
}());
exports.MultiSend__factory = MultiSend__factory;
