/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SafeToL2Setup,
  SafeToL2SetupInterface,
} from "../../../contracts/libraries/SafeToL2Setup";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "singleton",
        type: "address",
      },
    ],
    name: "ChangedMasterCopy",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "l2Singleton",
        type: "address",
      },
    ],
    name: "setupToL2",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class SafeToL2Setup__factory {
  static readonly abi = _abi;
  static createInterface(): SafeToL2SetupInterface {
    return new utils.Interface(_abi) as SafeToL2SetupInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SafeToL2Setup {
    return new Contract(address, _abi, signerOrProvider) as SafeToL2Setup;
  }
}
