"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SafeToL2Setup__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "singleton",
                type: "address",
            },
        ],
        name: "ChangedMasterCopy",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "l2Singleton",
                type: "address",
            },
        ],
        name: "setupToL2",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
var SafeToL2Setup__factory = /** @class */ (function () {
    function SafeToL2Setup__factory() {
    }
    SafeToL2Setup__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    SafeToL2Setup__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    SafeToL2Setup__factory.abi = _abi;
    return SafeToL2Setup__factory;
}());
exports.SafeToL2Setup__factory = SafeToL2Setup__factory;
