"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OnlyOwnersGuard__factory = exports.ISafe__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ISafe__factory_1 = require("./ISafe__factory");
Object.defineProperty(exports, "ISafe__factory", { enumerable: true, get: function () { return ISafe__factory_1.ISafe__factory; } });
var OnlyOwnersGuard__factory_1 = require("./OnlyOwnersGuard__factory");
Object.defineProperty(exports, "OnlyOwnersGuard__factory", { enumerable: true, get: function () { return OnlyOwnersGuard__factory_1.OnlyOwnersGuard__factory; } });
