/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TestHandler,
  TestHandlerInterface,
} from "../../../contracts/test/TestHandler";

const _abi = [
  {
    inputs: [],
    name: "dudududu",
    outputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "manager",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class TestHandler__factory {
  static readonly abi = _abi;
  static createInterface(): TestHandlerInterface {
    return new utils.Interface(_abi) as TestHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestHandler {
    return new Contract(address, _abi, signerOrProvider) as TestHandler;
  }
}
