"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SafeProxy__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "_singleton",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        stateMutability: "payable",
        type: "fallback",
    },
];
var SafeProxy__factory = /** @class */ (function () {
    function SafeProxy__factory() {
    }
    SafeProxy__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    SafeProxy__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    SafeProxy__factory.abi = _abi;
    return SafeProxy__factory;
}());
exports.SafeProxy__factory = SafeProxy__factory;
