"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ViewStorageAccessible__factory = exports.ISignatureValidator__factory = exports.IERC165__factory = exports.ERC777TokensRecipient__factory = exports.ERC721TokenReceiver__factory = exports.ERC1155TokenReceiver__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ERC1155TokenReceiver__factory_1 = require("./ERC1155TokenReceiver__factory");
Object.defineProperty(exports, "ERC1155TokenReceiver__factory", { enumerable: true, get: function () { return ERC1155TokenReceiver__factory_1.ERC1155TokenReceiver__factory; } });
var ERC721TokenReceiver__factory_1 = require("./ERC721TokenReceiver__factory");
Object.defineProperty(exports, "ERC721TokenReceiver__factory", { enumerable: true, get: function () { return ERC721TokenReceiver__factory_1.ERC721TokenReceiver__factory; } });
var ERC777TokensRecipient__factory_1 = require("./ERC777TokensRecipient__factory");
Object.defineProperty(exports, "ERC777TokensRecipient__factory", { enumerable: true, get: function () { return ERC777TokensRecipient__factory_1.ERC777TokensRecipient__factory; } });
var IERC165__factory_1 = require("./IERC165__factory");
Object.defineProperty(exports, "IERC165__factory", { enumerable: true, get: function () { return IERC165__factory_1.IERC165__factory; } });
var ISignatureValidator__factory_1 = require("./ISignatureValidator__factory");
Object.defineProperty(exports, "ISignatureValidator__factory", { enumerable: true, get: function () { return ISignatureValidator__factory_1.ISignatureValidator__factory; } });
var ViewStorageAccessible__factory_1 = require("./ViewStorageAccessible__factory");
Object.defineProperty(exports, "ViewStorageAccessible__factory", { enumerable: true, get: function () { return ViewStorageAccessible__factory_1.ViewStorageAccessible__factory; } });
