"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ViewStorageAccessible__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "targetContract",
                type: "address",
            },
            {
                internalType: "bytes",
                name: "calldataPayload",
                type: "bytes",
            },
        ],
        name: "simulate",
        outputs: [
            {
                internalType: "bytes",
                name: "",
                type: "bytes",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
var ViewStorageAccessible__factory = /** @class */ (function () {
    function ViewStorageAccessible__factory() {
    }
    ViewStorageAccessible__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    ViewStorageAccessible__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    ViewStorageAccessible__factory.abi = _abi;
    return ViewStorageAccessible__factory;
}());
exports.ViewStorageAccessible__factory = ViewStorageAccessible__factory;
