"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.migrate130To120Sol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.migrate130To120Sol = require("./Migrate_1_3_0_to_1_2_0.sol");
