"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SafeToL2Migration__factory = exports.ISafe__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ISafe__factory_1 = require("./ISafe__factory");
Object.defineProperty(exports, "ISafe__factory", { enumerable: true, get: function () { return ISafe__factory_1.ISafe__factory; } });
var SafeToL2Migration__factory_1 = require("./SafeToL2Migration__factory");
Object.defineProperty(exports, "SafeToL2Migration__factory", { enumerable: true, get: function () { return SafeToL2Migration__factory_1.SafeToL2Migration__factory; } });
