"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SafeToL2Migration__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "singleton",
                type: "address",
            },
        ],
        name: "ChangedMasterCopy",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "to",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "value",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "bytes",
                name: "data",
                type: "bytes",
            },
            {
                indexed: false,
                internalType: "enum Enum.Operation",
                name: "operation",
                type: "uint8",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "safeTxGas",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "baseGas",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "gasPrice",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "gasToken",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address payable",
                name: "refundReceiver",
                type: "address",
            },
            {
                indexed: false,
                internalType: "bytes",
                name: "signatures",
                type: "bytes",
            },
            {
                indexed: false,
                internalType: "bytes",
                name: "additionalInfo",
                type: "bytes",
            },
        ],
        name: "SafeMultiSigTransaction",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "initiator",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address[]",
                name: "owners",
                type: "address[]",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "threshold",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "initializer",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address",
                name: "fallbackHandler",
                type: "address",
            },
        ],
        name: "SafeSetup",
        type: "event",
    },
    {
        inputs: [],
        name: "MIGRATION_SINGLETON",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "l2Singleton",
                type: "address",
            },
            {
                internalType: "address",
                name: "fallbackHandler",
                type: "address",
            },
        ],
        name: "migrateFromV111",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "l2Singleton",
                type: "address",
            },
        ],
        name: "migrateToL2",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
var SafeToL2Migration__factory = /** @class */ (function () {
    function SafeToL2Migration__factory() {
    }
    SafeToL2Migration__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    SafeToL2Migration__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    SafeToL2Migration__factory.abi = _abi;
    return SafeToL2Migration__factory;
}());
exports.SafeToL2Migration__factory = SafeToL2Migration__factory;
