"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SafeProxyFactory__factory = exports.IProxyCreationCallback__factory = exports.safeProxySol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.safeProxySol = require("./SafeProxy.sol");
var IProxyCreationCallback__factory_1 = require("./IProxyCreationCallback__factory");
Object.defineProperty(exports, "IProxyCreationCallback__factory", { enumerable: true, get: function () { return IProxyCreationCallback__factory_1.IProxyCreationCallback__factory; } });
var SafeProxyFactory__factory_1 = require("./SafeProxyFactory__factory");
Object.defineProperty(exports, "SafeProxyFactory__factory", { enumerable: true, get: function () { return SafeProxyFactory__factory_1.SafeProxyFactory__factory; } });
