"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NativeCurrencyPaymentFallback__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "value",
                type: "uint256",
            },
        ],
        name: "SafeReceived",
        type: "event",
    },
    {
        stateMutability: "payable",
        type: "receive",
    },
];
var NativeCurrencyPaymentFallback__factory = /** @class */ (function () {
    function NativeCurrencyPaymentFallback__factory() {
    }
    NativeCurrencyPaymentFallback__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    NativeCurrencyPaymentFallback__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    NativeCurrencyPaymentFallback__factory.abi = _abi;
    return NativeCurrencyPaymentFallback__factory;
}());
exports.NativeCurrencyPaymentFallback__factory = NativeCurrencyPaymentFallback__factory;
